// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// combine_simes
Rcpp::NumericVector combine_simes(Rcpp::List Pvals, bool logp);
RcppExport SEXP _metapod_combine_simes(SEXP PvalsSEXP, SEXP logpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type Pvals(PvalsSEXP);
    Rcpp::traits::input_parameter< bool >::type logp(logpSEXP);
    rcpp_result_gen = Rcpp::wrap(combine_simes(Pvals, logp));
    return rcpp_result_gen;
END_RCPP
}
// combine_holm_middle
Rcpp::NumericVector combine_holm_middle(Rcpp::List Pvals, bool logp, double prop);
RcppExport SEXP _metapod_combine_holm_middle(SEXP PvalsSEXP, SEXP logpSEXP, SEXP propSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type Pvals(PvalsSEXP);
    Rcpp::traits::input_parameter< bool >::type logp(logpSEXP);
    Rcpp::traits::input_parameter< double >::type prop(propSEXP);
    rcpp_result_gen = Rcpp::wrap(combine_holm_middle(Pvals, logp, prop));
    return rcpp_result_gen;
END_RCPP
}
// compute_Top_statistic_from_ranks
Rcpp::IntegerVector compute_Top_statistic_from_ranks(Rcpp::List Ranks, double prop);
RcppExport SEXP _metapod_compute_Top_statistic_from_ranks(SEXP RanksSEXP, SEXP propSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type Ranks(RanksSEXP);
    Rcpp::traits::input_parameter< double >::type prop(propSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Top_statistic_from_ranks(Ranks, prop));
    return rcpp_result_gen;
END_RCPP
}
// choose_middle_effect_size
Rcpp::NumericVector choose_middle_effect_size(Rcpp::List Pvals, Rcpp::List Effects, double prop);
RcppExport SEXP _metapod_choose_middle_effect_size(SEXP PvalsSEXP, SEXP EffectsSEXP, SEXP propSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type Pvals(PvalsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Effects(EffectsSEXP);
    Rcpp::traits::input_parameter< double >::type prop(propSEXP);
    rcpp_result_gen = Rcpp::wrap(choose_middle_effect_size(Pvals, Effects, prop));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metapod_combine_simes", (DL_FUNC) &_metapod_combine_simes, 2},
    {"_metapod_combine_holm_middle", (DL_FUNC) &_metapod_combine_holm_middle, 3},
    {"_metapod_compute_Top_statistic_from_ranks", (DL_FUNC) &_metapod_compute_Top_statistic_from_ranks, 2},
    {"_metapod_choose_middle_effect_size", (DL_FUNC) &_metapod_choose_middle_effect_size, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_metapod(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
