# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_parallel_simes <- function(pvals, weights, log) {
    .Call('_metapod_compute_parallel_simes', PACKAGE = 'metapod', pvals, weights, log)
}

compute_parallel_berger <- function(pvals, weights, log) {
    .Call('_metapod_compute_parallel_berger', PACKAGE = 'metapod', pvals, weights, log)
}

compute_parallel_holm_min <- function(pvals, weights, log, min_n, min_prop) {
    .Call('_metapod_compute_parallel_holm_min', PACKAGE = 'metapod', pvals, weights, log, min_n, min_prop)
}

compute_parallel_stouffer <- function(pvals, weights, log) {
    .Call('_metapod_compute_parallel_stouffer', PACKAGE = 'metapod', pvals, weights, log)
}

compute_parallel_fisher <- function(pvals, weights, log) {
    .Call('_metapod_compute_parallel_fisher', PACKAGE = 'metapod', pvals, weights, log)
}

combine_simes <- function(Pvals, logp) {
    .Call('_metapod_combine_simes', PACKAGE = 'metapod', Pvals, logp)
}

combine_holm_middle <- function(Pvals, logp, prop) {
    .Call('_metapod_combine_holm_middle', PACKAGE = 'metapod', Pvals, logp, prop)
}

compute_Top_statistic_from_ranks <- function(Ranks, prop) {
    .Call('_metapod_compute_Top_statistic_from_ranks', PACKAGE = 'metapod', Ranks, prop)
}

choose_middle_effect_size <- function(Pvals, Effects, prop) {
    .Call('_metapod_choose_middle_effect_size', PACKAGE = 'metapod', Pvals, Effects, prop)
}

